### ISSUE TITLE
costume keeps changing to basic fashion coupon costume durings bgs

### ISSUE THREAD

**Issue by Poilim** [hugedong69/arborean-apparel#6]
Whenever inside a BG, in case for FWC, during fighting my costume keeps changing to the basic fashion coupon costume. However the original costume gets reapplied whenever I die and resurrect at the base. I have never used AA today, so I don't have any costumes over my original. I also updated my tera-data folder but the issue still persists.

**Comment by emmjayh** [comment]
ReferenceError: dbid is not defined
    at Networking.ArboreanApparel.net.on (D:\TeraProxy\ElinGtera-proxy\bin\node_modules\arborean-apparel\index.js:648:9)
    at emitThree (events.js:116:13)
    at Networking.emit (events.js:197:7)
    at Interface.readline.createInterface.on (D:\TeraProxy\ElinGtera-proxy\bin\node_modules\arborean-apparel\networking.js:17:11)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)

This is the error that is thrown when this bug occurs, (it can also happen while opening bamarama boxes) loving the UI <3

**Comment by hugedong69** [comment]
Currently fixed, will push an update soon. Not too sure if the referenceerror is causing it as it's in a completely unrelated part but we'll see.

**Comment by hugedong69** [comment]
Update pushed, lemme know if I didn't fix it
